# Uncomment the following lines to define your default indexer and rpc urls
#indexer_url = ""
#rpc_url = ""
#masp_indexer_url = ""
#localnet_enabled = false
#fathom_site_id = ""

# [frontend_fee."*"]
# transparent_target = "tnam1..."
# shielded_target = "znam1..."
# percentage = 0.001

# [frontend_fee.tnam1...(TOKEN_ADDRESS)]
# transparent_target = "tnam1..."
# shielded_target = "znam1..."
# percentage = 0.0005
