# Uncomment the following lines to define your default indexer and rpc urls
#indexer_url = ""
#rpc_url = ""
#masp_indexer_url = ""
#localnet_enabled = false
#fathom_site_id = ""

[frontend_fee."*"]
transparent_target = "tnam1qrxsru5rdu4he400xny6p779fcw7xuftsgjnmzup"
shielded_target = "znam1494fmm9qd4frr7jrydnxlcyt57nhngzutxnzgh6y70mkvh23d9z0jk2aasxh4p8dn2kczlgpans"
percentage = 0.01

