name: Docker Faucet 🐳

on:
  push:
    tags:
      - faucet@v*
    branches:
      - main

env:
  GIT_LFS_SKIP_SMUDGE: 1

permissions:
  id-token: write
  contents: write
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        images:
          - path: "docker/faucet/Dockerfile"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine Image Tag
        id: tag
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/faucet@v* ]]; then
            echo "IMAGE_TAG=faucet-${GITHUB_REF#refs/tags/faucet@}" >> $GITHUB_ENV
          else
            echo "IMAGE_TAG=faucet-main" >> $GITHUB_ENV
          fi

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository_owner }}/faucet
          tags: |
            type=raw,value=${{ env.IMAGE_TAG }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.images.path }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
